# Generated by Django 4.0 on 2022-04-15 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('BDA', 'Business Development Executive'), ('CS', 'Customer Support'), ('IS', 'Inside Sales'), ('CW', 'Content Writing'), ('DM', 'Digital Marketing')], max_length=5)),
                ('description', models.CharField(max_length=60)),
                ('place', models.CharField(max_length=60)),
                ('phone', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
